#.travis.yml

sudo: required
dist: trusty

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install

script:
  - ng test --watch false
  - npm run dist && npm run fixdist

after_success:
  if [ "$TRAVIS_BRANCH" == "master" ] ; then
    if [ "x$DEPLOY_HOST$DEPLOY_PATH$DEPLOY_USER$DEPLOY_PASSWORD" != "x" ] ; then
      npm run deploy;
    else
      echo "Deployment missing environment variables $DEPLOY_(HOST,PATH,USERNAME,PASSWORD)." ;
    fi
  else
    echo "Deployment omitted.";
  fi

notifications:
  email:
    on_failure: change
    on_success: change